# Generated by Django 5.1.6 on 2025-02-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liverscan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="proxy_arterial_ct",
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="proxy_portal_venous_ct",
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="proxy_transformed_ct",
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="proxy_unenhanced_ct",
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
    ]
